# Generated by Django 5.2.3 on 2025-07-14 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grievance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='first',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
