# Generated by Django 5.2.3 on 2025-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grievance', '0004_login_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_data',
            name='images',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='images/'),
        ),
    ]
