# Generated by Django 5.2.3 on 2025-07-23 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grievance', '0005_alter_report_data_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_data',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='report_data',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
