# Generated by Django 5.2.5 on 2025-09-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grievance', '0007_register_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_data',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
