# Generated by Django 5.2.5 on 2025-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grievance', '0008_report_data_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_data',
            name='id',
        ),
        migrations.AddField(
            model_name='register_data',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
