# Generated by Django 5.2.5 on 2025-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grievance', '0009_remove_register_data_id_register_data_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_data',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='report_data',
            name='id',
        ),
        migrations.AddField(
            model_name='register_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='report_data',
            name='status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
